var annotated_dup =
[
    [ "alt", "d6/d94/namespacealt.html", [
      [ "db", "da/d84/namespacealt_1_1db.html", [
        [ "Core", "dd/d40/classalt_1_1db_1_1_core.html", "dd/d40/classalt_1_1db_1_1_core" ],
        [ "Engine", "d7/d71/classalt_1_1db_1_1_engine.html", "d7/d71/classalt_1_1db_1_1_engine" ],
        [ "Statement", "da/d34/classalt_1_1db_1_1_statement.html", "da/d34/classalt_1_1db_1_1_statement" ]
      ] ],
      [ "ex", "d6/d32/namespacealt_1_1ex.html", [
        [ "Exception", "d9/d47/classalt_1_1ex_1_1_exception.html", "d9/d47/classalt_1_1ex_1_1_exception" ],
        [ "InvalidArgumentException", "da/d30/classalt_1_1ex_1_1_invalid_argument_exception.html", "da/d30/classalt_1_1ex_1_1_invalid_argument_exception" ],
        [ "RuntimeException", "df/da4/classalt_1_1ex_1_1_runtime_exception.html", "df/da4/classalt_1_1ex_1_1_runtime_exception" ]
      ] ],
      [ "FactoryMethod", "df/d81/namespacealt_1_1_factory_method.html", [
        [ "ByteData", "dc/d00/classalt_1_1_factory_method_1_1_byte_data.html", "dc/d00/classalt_1_1_factory_method_1_1_byte_data" ],
        [ "ClockElement", "d5/dcb/classalt_1_1_factory_method_1_1_clock_element.html", "d5/dcb/classalt_1_1_factory_method_1_1_clock_element" ],
        [ "Config", "db/d43/classalt_1_1_factory_method_1_1_config.html", "db/d43/classalt_1_1_factory_method_1_1_config" ],
        [ "Creator", "d8/d15/classalt_1_1_factory_method_1_1_creator.html", "d8/d15/classalt_1_1_factory_method_1_1_creator" ],
        [ "DummyProduct", "d8/da8/classalt_1_1_factory_method_1_1_dummy_product.html", "d8/da8/classalt_1_1_factory_method_1_1_dummy_product" ],
        [ "IConfig", "d6/d9a/classalt_1_1_factory_method_1_1_i_config.html", "d6/d9a/classalt_1_1_factory_method_1_1_i_config" ],
        [ "ICreator", "d5/d5b/classalt_1_1_factory_method_1_1_i_creator.html", "d5/d5b/classalt_1_1_factory_method_1_1_i_creator" ],
        [ "IData", "d1/d90/classalt_1_1_factory_method_1_1_i_data.html", "d1/d90/classalt_1_1_factory_method_1_1_i_data" ],
        [ "IElement", "de/d54/classalt_1_1_factory_method_1_1_i_element.html", "de/d54/classalt_1_1_factory_method_1_1_i_element" ],
        [ "IFactoryMethod", "d9/db8/classalt_1_1_factory_method_1_1_i_factory_method.html", "d9/db8/classalt_1_1_factory_method_1_1_i_factory_method" ],
        [ "IMessage", "dc/dd3/classalt_1_1_factory_method_1_1_i_message.html", "dc/dd3/classalt_1_1_factory_method_1_1_i_message" ],
        [ "IProduct", "d8/d52/classalt_1_1_factory_method_1_1_i_product.html", "d8/d52/classalt_1_1_factory_method_1_1_i_product" ],
        [ "IProductManager", "d7/d26/classalt_1_1_factory_method_1_1_i_product_manager.html", "d7/d26/classalt_1_1_factory_method_1_1_i_product_manager" ],
        [ "PipelineFactoryMethod", "d5/d5c/classalt_1_1_factory_method_1_1_pipeline_factory_method.html", "d5/d5c/classalt_1_1_factory_method_1_1_pipeline_factory_method" ],
        [ "ProductManager", "dd/dae/classalt_1_1_factory_method_1_1_product_manager.html", "dd/dae/classalt_1_1_factory_method_1_1_product_manager" ],
        [ "QueueElement", "db/dc2/classalt_1_1_factory_method_1_1_queue_element.html", "db/dc2/classalt_1_1_factory_method_1_1_queue_element" ],
        [ "SyncElement", "d9/d3b/classalt_1_1_factory_method_1_1_sync_element.html", "d9/d3b/classalt_1_1_factory_method_1_1_sync_element" ],
        [ "TerminateElement", "da/d9a/classalt_1_1_factory_method_1_1_terminate_element.html", "da/d9a/classalt_1_1_factory_method_1_1_terminate_element" ]
      ] ],
      [ "skeleton", "d7/d0a/namespacealt_1_1skeleton.html", [
        [ "Array", "db/d6a/classalt_1_1skeleton_1_1_array.html", "db/d6a/classalt_1_1skeleton_1_1_array" ],
        [ "Binder", "dd/d88/classalt_1_1skeleton_1_1_binder.html", "dd/d88/classalt_1_1skeleton_1_1_binder" ],
        [ "Command", "d9/ddf/classalt_1_1skeleton_1_1_command.html", "d9/ddf/classalt_1_1skeleton_1_1_command" ],
        [ "Commander", "de/d2d/classalt_1_1skeleton_1_1_commander.html", "de/d2d/classalt_1_1skeleton_1_1_commander" ],
        [ "CompositeLeaf", "d9/da4/classalt_1_1skeleton_1_1_composite_leaf.html", "d9/da4/classalt_1_1skeleton_1_1_composite_leaf" ],
        [ "CompositeNode", "dc/d17/classalt_1_1skeleton_1_1_composite_node.html", "dc/d17/classalt_1_1skeleton_1_1_composite_node" ],
        [ "Freight", "d6/df8/classalt_1_1skeleton_1_1_freight.html", "d6/df8/classalt_1_1skeleton_1_1_freight" ],
        [ "ICallback", "d2/dd0/classalt_1_1skeleton_1_1_i_callback.html", "d2/dd0/classalt_1_1skeleton_1_1_i_callback" ],
        [ "IConsumer", "d9/d58/classalt_1_1skeleton_1_1_i_consumer.html", "d9/d58/classalt_1_1skeleton_1_1_i_consumer" ],
        [ "IFunction", "d6/d9b/classalt_1_1skeleton_1_1_i_function.html", "d6/d9b/classalt_1_1skeleton_1_1_i_function" ],
        [ "IMemory", "d6/d93/classalt_1_1skeleton_1_1_i_memory.html", "d6/d93/classalt_1_1skeleton_1_1_i_memory" ],
        [ "IObserver", "df/d7b/classalt_1_1skeleton_1_1_i_observer.html", "df/d7b/classalt_1_1skeleton_1_1_i_observer" ],
        [ "IPredicate", "d1/d49/classalt_1_1skeleton_1_1_i_predicate.html", "d1/d49/classalt_1_1skeleton_1_1_i_predicate" ],
        [ "ISubscriber", "db/d5c/classalt_1_1skeleton_1_1_i_subscriber.html", "db/d5c/classalt_1_1skeleton_1_1_i_subscriber" ],
        [ "ISupplier", "d3/d12/classalt_1_1skeleton_1_1_i_supplier.html", "d3/d12/classalt_1_1skeleton_1_1_i_supplier" ],
        [ "ITimeup", "db/dbd/classalt_1_1skeleton_1_1_i_timeup.html", "db/dbd/classalt_1_1skeleton_1_1_i_timeup" ],
        [ "LinkedList", "dc/d73/classalt_1_1skeleton_1_1_linked_list.html", "dc/d73/classalt_1_1skeleton_1_1_linked_list" ],
        [ "LinkedListIterator", "d3/d31/classalt_1_1skeleton_1_1_linked_list_iterator.html", "d3/d31/classalt_1_1skeleton_1_1_linked_list_iterator" ],
        [ "LinkedListNode", "d2/dbb/classalt_1_1skeleton_1_1_linked_list_node.html", "d2/dbb/classalt_1_1skeleton_1_1_linked_list_node" ],
        [ "Map", "df/d69/classalt_1_1skeleton_1_1_map.html", "df/d69/classalt_1_1skeleton_1_1_map" ],
        [ "MapIterator", "d8/d3a/classalt_1_1skeleton_1_1_map_iterator.html", "d8/d3a/classalt_1_1skeleton_1_1_map_iterator" ],
        [ "MapNode", "d3/d09/classalt_1_1skeleton_1_1_map_node.html", "d3/d09/classalt_1_1skeleton_1_1_map_node" ],
        [ "Singleton", "d0/d37/classalt_1_1skeleton_1_1_singleton.html", "d0/d37/classalt_1_1skeleton_1_1_singleton" ],
        [ "Strategy", "de/d3b/classalt_1_1skeleton_1_1_strategy.html", "de/d3b/classalt_1_1skeleton_1_1_strategy" ]
      ] ],
      [ "BasicMemory", "d3/d1a/classalt_1_1_basic_memory.html", "d3/d1a/classalt_1_1_basic_memory" ],
      [ "Console", "d1/de5/classalt_1_1_console.html", "d1/de5/classalt_1_1_console" ],
      [ "CriticalSection", "d4/d33/classalt_1_1_critical_section.html", "d4/d33/classalt_1_1_critical_section" ],
      [ "Data", "db/d63/classalt_1_1_data.html", "db/d63/classalt_1_1_data" ],
      [ "DBLibrary", "dc/d53/classalt_1_1_d_b_library.html", "dc/d53/classalt_1_1_d_b_library" ],
      [ "Diagnostics", "d8/d52/classalt_1_1_diagnostics.html", "d8/d52/classalt_1_1_diagnostics" ],
      [ "Event", "d1/d4d/classalt_1_1_event.html", "d1/d4d/classalt_1_1_event" ],
      [ "File", "d1/dfc/classalt_1_1_file.html", "d1/dfc/classalt_1_1_file" ],
      [ "FileInfo", "de/da5/classalt_1_1_file_info.html", "de/da5/classalt_1_1_file_info" ],
      [ "FileInfo1", "d8/d2d/classalt_1_1_file_info1.html", "d8/d2d/classalt_1_1_file_info1" ],
      [ "FileInfo2", "d7/d08/classalt_1_1_file_info2.html", "d7/d08/classalt_1_1_file_info2" ],
      [ "FileUtility", "d3/d85/classalt_1_1_file_utility.html", "d3/d85/classalt_1_1_file_utility" ],
      [ "HandleLibrary", "d0/d99/classalt_1_1_handle_library.html", "d0/d99/classalt_1_1_handle_library" ],
      [ "HeapMemory", "da/d83/classalt_1_1_heap_memory.html", "da/d83/classalt_1_1_heap_memory" ],
      [ "Log", "d8/dfd/classalt_1_1_log.html", "d8/dfd/classalt_1_1_log" ],
      [ "Message", "d5/d42/classalt_1_1_message.html", "d5/d42/classalt_1_1_message" ],
      [ "MiddleLibrary", "d9/dfd/classalt_1_1_middle_library.html", "d9/dfd/classalt_1_1_middle_library" ],
      [ "Mutex", "d0/d5c/classalt_1_1_mutex.html", "d0/d5c/classalt_1_1_mutex" ],
      [ "NamedPipe", "d9/de1/classalt_1_1_named_pipe.html", "d9/de1/classalt_1_1_named_pipe" ],
      [ "PerformanceDataHelper", "dc/d26/classalt_1_1_performance_data_helper.html", "dc/d26/classalt_1_1_performance_data_helper" ],
      [ "PerformanceDataItem", "dc/d63/classalt_1_1_performance_data_item.html", "dc/d63/classalt_1_1_performance_data_item" ],
      [ "Pipe", "d3/d32/classalt_1_1_pipe.html", "d3/d32/classalt_1_1_pipe" ],
      [ "Process", "d6/d3f/classalt_1_1_process.html", "d6/d3f/classalt_1_1_process" ],
      [ "QueryPerformance", "d4/d2d/classalt_1_1_query_performance.html", "d4/d2d/classalt_1_1_query_performance" ],
      [ "ReadWriteHandleLibrary", "d2/d8c/classalt_1_1_read_write_handle_library.html", "d2/d8c/classalt_1_1_read_write_handle_library" ],
      [ "RingBuffer", "db/da2/classalt_1_1_ring_buffer.html", "db/da2/classalt_1_1_ring_buffer" ],
      [ "SharedMemory", "d5/d53/classalt_1_1_shared_memory.html", "d5/d53/classalt_1_1_shared_memory" ],
      [ "SocketBuilder", "dd/db7/classalt_1_1_socket_builder.html", "dd/db7/classalt_1_1_socket_builder" ],
      [ "SocketLibrary", "d8/d51/classalt_1_1_socket_library.html", "d8/d51/classalt_1_1_socket_library" ],
      [ "TcpConnector", "d3/d45/classalt_1_1_tcp_connector.html", "d3/d45/classalt_1_1_tcp_connector" ],
      [ "Thread", "d0/df1/classalt_1_1_thread.html", "d0/df1/classalt_1_1_thread" ],
      [ "TransactionFile", "d4/d3b/classalt_1_1_transaction_file.html", "d4/d3b/classalt_1_1_transaction_file" ],
      [ "TransactionFileUtility", "dc/d44/classalt_1_1_transaction_file_utility.html", "dc/d44/classalt_1_1_transaction_file_utility" ],
      [ "TString", "d2/dd0/classalt_1_1_t_string.html", "d2/dd0/classalt_1_1_t_string" ],
      [ "UdpConnector", "d3/d2b/classalt_1_1_udp_connector.html", "d3/d2b/classalt_1_1_udp_connector" ],
      [ "Utility", "d9/d84/classalt_1_1_utility.html", "d9/d84/classalt_1_1_utility" ],
      [ "VirtualMemory", "d9/d1e/classalt_1_1_virtual_memory.html", "d9/d1e/classalt_1_1_virtual_memory" ],
      [ "VirtualMemory1", "d8/d77/classalt_1_1_virtual_memory1.html", "d8/d77/classalt_1_1_virtual_memory1" ],
      [ "WaitableHandleLibrary", "d1/d35/classalt_1_1_waitable_handle_library.html", "d1/d35/classalt_1_1_waitable_handle_library" ],
      [ "WatchDogTimer", "d5/db9/classalt_1_1_watch_dog_timer.html", "d5/db9/classalt_1_1_watch_dog_timer" ],
      [ "WindowsLibrary", "de/dcb/classalt_1_1_windows_library.html", "de/dcb/classalt_1_1_windows_library" ],
      [ "WorkerFunction", "db/d8c/classalt_1_1_worker_function.html", "db/d8c/classalt_1_1_worker_function" ],
      [ "WorkerTemplate", "d6/d9a/classalt_1_1_worker_template.html", "d6/d9a/classalt_1_1_worker_template" ]
    ] ],
    [ "LeakCheck", "dc/de5/namespace_leak_check.html", [
      [ "ArrayMemoryLeakCheck", "dd/dc4/class_leak_check_1_1_array_memory_leak_check.html", "dd/dc4/class_leak_check_1_1_array_memory_leak_check" ],
      [ "BinderMemoryLeakCheck", "d7/d0a/class_leak_check_1_1_binder_memory_leak_check.html", "d7/d0a/class_leak_check_1_1_binder_memory_leak_check" ],
      [ "Data", "d2/d71/class_leak_check_1_1_data.html", "d2/d71/class_leak_check_1_1_data" ],
      [ "FreightMemoryLeakCheck", "db/d3e/class_leak_check_1_1_freight_memory_leak_check.html", "db/d3e/class_leak_check_1_1_freight_memory_leak_check" ],
      [ "LeakCheck", "db/db4/class_leak_check_1_1_leak_check.html", "db/db4/class_leak_check_1_1_leak_check" ],
      [ "LeakCheckTest", "d5/dbe/class_leak_check_1_1_leak_check_test.html", "d5/dbe/class_leak_check_1_1_leak_check_test" ],
      [ "LinkedListMemoryLeakCheck", "de/dce/class_leak_check_1_1_linked_list_memory_leak_check.html", "de/dce/class_leak_check_1_1_linked_list_memory_leak_check" ],
      [ "TStringMemoryLeakCheck", "d9/d10/class_leak_check_1_1_t_string_memory_leak_check.html", "d9/d10/class_leak_check_1_1_t_string_memory_leak_check" ]
    ] ],
    [ "oss", "d2/d84/namespaceoss.html", [
      [ "OSSLibrary", "d2/d40/classoss_1_1_o_s_s_library.html", "d2/d40/classoss_1_1_o_s_s_library" ]
    ] ],
    [ "PerfCheck", "d1/d3d/namespace_perf_check.html", [
      [ "_WatchDogData", "df/d12/struct_perf_check_1_1___watch_dog_data.html", "df/d12/struct_perf_check_1_1___watch_dog_data" ],
      [ "ArrayPerformanceCheck", "d8/dbf/class_perf_check_1_1_array_performance_check.html", "d8/dbf/class_perf_check_1_1_array_performance_check" ],
      [ "ConsolePerformanceCheck", "d8/d50/class_perf_check_1_1_console_performance_check.html", "d8/d50/class_perf_check_1_1_console_performance_check" ],
      [ "DequePerformanceCheck", "df/db5/class_perf_check_1_1_deque_performance_check.html", "df/db5/class_perf_check_1_1_deque_performance_check" ],
      [ "DownstreamDriver", "d6/d1f/class_perf_check_1_1_downstream_driver.html", "d6/d1f/class_perf_check_1_1_downstream_driver" ],
      [ "FilePerformanceCheck", "d1/d7a/class_perf_check_1_1_file_performance_check.html", "d1/d7a/class_perf_check_1_1_file_performance_check" ],
      [ "FreightPerformanceCheck", "db/dee/class_perf_check_1_1_freight_performance_check.html", "db/dee/class_perf_check_1_1_freight_performance_check" ],
      [ "HeapPerformanceCheck", "db/dbe/class_perf_check_1_1_heap_performance_check.html", "db/dbe/class_perf_check_1_1_heap_performance_check" ],
      [ "LinkedListPerformanceCheck", "df/d93/class_perf_check_1_1_linked_list_performance_check.html", "df/d93/class_perf_check_1_1_linked_list_performance_check" ],
      [ "NewPerformanceCheck", "d0/d31/class_perf_check_1_1_new_performance_check.html", "d0/d31/class_perf_check_1_1_new_performance_check" ],
      [ "PerformanceCheck", "d5/d0c/class_perf_check_1_1_performance_check.html", "d5/d0c/class_perf_check_1_1_performance_check" ],
      [ "ServerWorker", "df/d72/class_perf_check_1_1_server_worker.html", "df/d72/class_perf_check_1_1_server_worker" ],
      [ "StdFilePerformanceCheck", "d1/dbe/class_perf_check_1_1_std_file_performance_check.html", "d1/dbe/class_perf_check_1_1_std_file_performance_check" ],
      [ "TcpClient", "d7/de9/class_perf_check_1_1_tcp_client.html", "d7/de9/class_perf_check_1_1_tcp_client" ],
      [ "TCPPerformanceCheck", "da/d9c/class_perf_check_1_1_t_c_p_performance_check.html", "da/d9c/class_perf_check_1_1_t_c_p_performance_check" ],
      [ "TcpProxy", "dd/d18/class_perf_check_1_1_tcp_proxy.html", "dd/d18/class_perf_check_1_1_tcp_proxy" ],
      [ "TcpServer", "d9/d82/class_perf_check_1_1_tcp_server.html", "d9/d82/class_perf_check_1_1_tcp_server" ],
      [ "TStringPerformanceCheck", "d6/d10/class_perf_check_1_1_t_string_performance_check.html", "d6/d10/class_perf_check_1_1_t_string_performance_check" ],
      [ "UdpController", "dc/d1c/class_perf_check_1_1_udp_controller.html", "dc/d1c/class_perf_check_1_1_udp_controller" ],
      [ "UDPPerformanceCheck", "de/d39/class_perf_check_1_1_u_d_p_performance_check.html", "de/d39/class_perf_check_1_1_u_d_p_performance_check" ],
      [ "UpstreamDriver", "d3/d1b/class_perf_check_1_1_upstream_driver.html", "d3/d1b/class_perf_check_1_1_upstream_driver" ],
      [ "VectorPerformanceCheck", "da/de7/class_perf_check_1_1_vector_performance_check.html", "da/de7/class_perf_check_1_1_vector_performance_check" ],
      [ "WatchDocTimerPerformanceCheck", "d6/d59/class_perf_check_1_1_watch_doc_timer_performance_check.html", "d6/d59/class_perf_check_1_1_watch_doc_timer_performance_check" ]
    ] ],
    [ "picojson", "d4/d58/namespacepicojson.html", [
      [ "default_parse_context", "df/d0e/classpicojson_1_1default__parse__context.html", "df/d0e/classpicojson_1_1default__parse__context" ],
      [ "deny_parse_context", "df/d6d/classpicojson_1_1deny__parse__context.html", "df/d6d/classpicojson_1_1deny__parse__context" ],
      [ "input", "d0/d1f/classpicojson_1_1input.html", "d0/d1f/classpicojson_1_1input" ],
      [ "last_error_t", "d4/d87/structpicojson_1_1last__error__t.html", "d4/d87/structpicojson_1_1last__error__t" ],
      [ "null", "d6/d27/structpicojson_1_1null.html", null ],
      [ "null_parse_context", "d5/d62/classpicojson_1_1null__parse__context.html", "d5/d62/classpicojson_1_1null__parse__context" ],
      [ "serialize_str_char", "dd/dba/structpicojson_1_1serialize__str__char.html", "dd/dba/structpicojson_1_1serialize__str__char" ],
      [ "value", "de/d41/classpicojson_1_1value.html", "de/d41/classpicojson_1_1value" ]
    ] ],
    [ "_container", "d4/d3c/struct__container.html", "d4/d3c/struct__container" ],
    [ "fts5_api", "da/d3a/structfts5__api.html", "da/d3a/structfts5__api" ],
    [ "fts5_tokenizer", "d7/d6f/structfts5__tokenizer.html", "d7/d6f/structfts5__tokenizer" ],
    [ "Fts5ExtensionApi", "d8/d3b/struct_fts5_extension_api.html", "d8/d3b/struct_fts5_extension_api" ],
    [ "Fts5PhraseIter", "da/d31/struct_fts5_phrase_iter.html", "da/d31/struct_fts5_phrase_iter" ],
    [ "InvalidArgmentException", "d1/d72/class_invalid_argment_exception.html", null ],
    [ "MemoryLeakCheck", "dc/d39/class_memory_leak_check.html", null ],
    [ "sqlite3_file", "db/db0/structsqlite3__file.html", "db/db0/structsqlite3__file" ],
    [ "sqlite3_index_info", "d2/d4a/structsqlite3__index__info.html", "d2/d4a/structsqlite3__index__info" ],
    [ "sqlite3_io_methods", "d9/df3/structsqlite3__io__methods.html", "d9/df3/structsqlite3__io__methods" ],
    [ "sqlite3_mem_methods", "d4/d9a/structsqlite3__mem__methods.html", "d4/d9a/structsqlite3__mem__methods" ],
    [ "sqlite3_module", "dd/de4/structsqlite3__module.html", "dd/de4/structsqlite3__module" ],
    [ "sqlite3_mutex_methods", "da/de2/structsqlite3__mutex__methods.html", "da/de2/structsqlite3__mutex__methods" ],
    [ "sqlite3_pcache_methods", "d7/d71/structsqlite3__pcache__methods.html", "d7/d71/structsqlite3__pcache__methods" ],
    [ "sqlite3_pcache_methods2", "df/dca/structsqlite3__pcache__methods2.html", "df/dca/structsqlite3__pcache__methods2" ],
    [ "sqlite3_pcache_page", "d8/d72/structsqlite3__pcache__page.html", "d8/d72/structsqlite3__pcache__page" ],
    [ "sqlite3_rtree_geometry", "d8/d14/structsqlite3__rtree__geometry.html", "d8/d14/structsqlite3__rtree__geometry" ],
    [ "sqlite3_rtree_query_info", "d9/df9/structsqlite3__rtree__query__info.html", "d9/df9/structsqlite3__rtree__query__info" ],
    [ "sqlite3_snapshot", "db/db4/structsqlite3__snapshot.html", "db/db4/structsqlite3__snapshot" ],
    [ "sqlite3_vfs", "d3/d36/structsqlite3__vfs.html", "d3/d36/structsqlite3__vfs" ],
    [ "sqlite3_vtab", "d3/d12/structsqlite3__vtab.html", "d3/d12/structsqlite3__vtab" ],
    [ "sqlite3_vtab_cursor", "d3/d17/structsqlite3__vtab__cursor.html", "d3/d17/structsqlite3__vtab__cursor" ],
    [ "WatchDogData", "de/d1b/struct_watch_dog_data.html", null ]
];